### ISSUE TITLE
how to use wildcards in koa-route

### ISSUE THREAD

**Issue by dsgygb** [koajs/route#26]
var path = require('path')
    var route= require('koa-route');//路由
    app.use(route.get('/api/*',api.before));

I can't use it for this,how should I use wildcards in koa-route? Or,which other can do ?

**Comment by coderhaoxin** [comment]
see https://github.com/pillarjs/path-to-regexp#unnamed-parameters

```js
app.use(route.get('/api/(.*)',api.before));
```

**Comment by dsgygb** [comment]
app.use(route.get('/api/(.*)',api.before));
    app.use(route.get('/api/test',api.test));

I want to goto '/api/test',I use above,but it can't word,how to do?

**Comment by tj** [comment]
@dsgygb order still matters, try "test" above the greedier version:

```
app.use(route.get('/api/(.*)',api.before));
app.use(route.get('/api/test',api.test));
```

**Comment by coderhaoxin** [comment]
@dsgygb you need `yield next`, like

```
app.use(route.get('/api/(.*)', function*(path, next){
  // do something ...
  yield next;
}));
app.use(route.get('/api/test',api.test));
```

**Comment by dsgygb** [comment]
thank you! resolve my question！
