### ISSUE TITLE
How do I get POST parameters?

### ISSUE THREAD

**Issue by thelinuxlich** [koajs/route#30]
Sending parameters with superagent for testing, how do I get the params object on the server?

**Comment by coderhaoxin** [comment]
such as:

```js
app.use(route.get('/users/:id', function*(id) {
  // ...
}))
```

**Comment by thelinuxlich** [comment]
not fixed parameters like that

**Comment by gsogc** [comment]
you can get POST

route.post(...)

**Comment by danneu** [comment]
I guess you're talking about reading form body params in your route.

koa-route doesn't parse those out of the request body. check out body-parsing middleware like https://github.com/koajs/bodyparser to get access to `this.request.body` which will be a map of the params.

**Comment by tejasmanohar** [comment]
@thelinuxlich *ping* - does @danneu's advice solve your issue? :)

**Comment by thelinuxlich** [comment]
Yes it does! Sorry I forgot to close

**Comment by tejasmanohar** [comment]
:)
