### ISSUE TITLE
Possible for Same Route Pattern but Different Types Data?

### ISSUE THREAD

**Issue by dschinkel** [koajs/route#32]
delete

**Comment by coderhaoxin** [comment]
Maybe this is useful for you https://github.com/pillarjs/path-to-regexp#custom-match-parameters

**Comment by tejasmanohar** [comment]
@dschinkel _ping_ - does @coderhaoxin's advice solve your issue? :)

**Comment by dschinkel** [comment]
No but it's a good link though.  I figured it out...
