### ISSUE TITLE
use with koa-send

### ISSUE THREAD

**Issue by 75lb** [koajs/route#41]
how do i use koa-route v3 (new promise api) with koa-send 3.1 (old generator api)? are they compatible at all? 

This example doesn't work - `send(ctx, url)` returns `co(function *(){ blah })`, in this case..
```
app.use(_.all('*', function (ctx, route, next) {
  send(ctx, url)
  return next()
}))
```

**Comment by tejasmanohar** [comment]
This isn't an issue with [koa-route](https://github.com/koajs/route), as the same applies with Koa v2 *without* the router. It doesn't look like [koa-send](https://github.com/koajs/send) has been updated for Koa v2, but PRs there are certainly welcomed.

Note that Koa v2 is in alpha so most middleware hasn't been updated (in and out of this [org](https://github.com/koajs)). It may be a long while before Koa v2 is released as latest/stable on npm. Check out https://github.com/koajs/koa/issues/533 (and voice your opinion if you don't mind).

**Comment by gyson** [comment]
I think koa-send has been updated (koajs/send#37) to Promise, which is what `co(function * () { ... })` returns.

It works for both v1 and v2.

For example, in v2

```js
app.use(_.all('*', function (ctx, route, next) {
  return send(ctx, url).then(() => next())
}))

// or

app.use(_.all('*', co.wrap(function * (ctx, route, next) {
  yield send(ctx, url)
  yield next()
})))
```

**Comment by tejasmanohar** [comment]
Aha, I see. So, yes, if you're using a version of koa-send with a Promise-based API, then all you're missing is the _then_ handler (.then(), await, etc.). @75lb

**Comment by 75lb** [comment]
thanks, the `return send(ctx, url).then(next)` approach fixed my issue.. i wasn't aware of this new return sig, does the koa-send README need updating?

> It may also be a long while before Koa v2 is released as latest/stable on npm

koa v2 is **already** the `latest` release on npm.. with npm 3.5, installing koa installs koa v2:

```
$ npm i koa --save
/Users/lloyd/tmp
└── koa@2.0.0-alpha.3
```

**Comment by 75lb** [comment]
npm's policy regarding prerelease versions at `latest` [changed recently](https://github.com/npm/npm/releases/tag/v3.4.1)

**Comment by tejasmanohar** [comment]
ooh, that's a problem. see https://github.com/koajs/koa/issues/533 (good bit of scrolling to do) - this is an ongoing issue about koa 1 vs 2 and when to release what as what. maybe pitch in there?

about not having koa-send docs up-to-date, yeah- agreed. just opened an issue here- https://github.com/koajs/send/issues/42. a bit busy today so may be able to get to it in the evening, maybe not... PRs are certainly welcomed for these types of things since you got it working :)
