### ISSUE TITLE
3.0.0 changelog

### ISSUE THREAD

**Issue by stephenmathieson** [koajs/route#42]
what happened from 2.x -> 3???

**Comment by tejasmanohar** [comment]
https://github.com/koajs/route/commit/2eabbca21d5edaa55ce9fc697ef38ab936cb1e44 -> this is for promise-based middleware in v2 of koa. please see https://github.com/koajs/koa/issues/533 :)

**Comment by greim** [comment]
Koa 2.0 isn't released yet, so people installing both get breakage. Should definitely post a warning

**Comment by tejasmanohar** [comment]
Though https://github.com/koajs/koa/issues/533 is still up in the air, I think I'll go ahead and make `master` contain koa v1 stuff with npm latest tag so that's what you get when you `npm install` and put koa v2 stuff on a non-master branch.... unless there are any significant objections.

thoughts @greim @stephenmathieson ?

**Comment by tejasmanohar** [comment]
@greim in latest npm, koa-route@2 should be `latest` https://github.com/npm/npm/releases/tag/v2.14.11. didn't realize this changed.

**Comment by tejasmanohar** [comment]
changed koa-route@latest to 2.4.2 so this is what you get when you `npm install` in v3. open to PRs for other warnings / notices in readme, postinstall, etc. @greim @stephenmathieson

**Comment by tj** [comment]
not sure if npm is smart enough to grab 2.4.x with peer deps or not but that might help

**Comment by stephenmathieson** [comment]
since koa is at 2.x.x-alpha, shouldn't this be 3.x.x-alpha too? I'd argue that `npm install koa koa-route` should work

**Comment by stephenmathieson** [comment]
meh npm removed unpublish, nvm

**Comment by tejasmanohar** [comment]
```
$ npm dist-tags ls koa
latest: 2.0.0-alpha.3

$ npm dist-tags ls koa-route
latest: 2.4.2
```

Someone with access to `koa` on NPM should make .

**Comment by tejasmanohar** [comment]
Anyways, I'll note this in #533
