### ISSUE TITLE
Will you have a plan to upgrade route to suite koa2?

### ISSUE THREAD

**Issue by cpselvis** [koajs/route#50]
Recently I tried to use koa next version to build a web app, after I installed koa middleware dependencies like koa-route, I found some issues from terminal. It indicated that I use old-signature-middleware-v1x.  app.use()  this syntax sugar will be deprecated in koa v3.

So I want to ask will you have a plan to upgrade route to suite koa2?

**Comment by coderhaoxin** [comment]
checkout https://github.com/koajs/route/tree/next

try

```
npm i koa-route@next
```

to install ((>_<))
