### ISSUE TITLE
Publish async/await version on NPM

### ISSUE THREAD

**Issue by ronkorving** [koajs/route#51]
Hi there

I'm trying out Koa with Node.js 7 using async/await. Since this router is on the official koajs organization, I figured this is where I should start my routing endeavour. Unfortunately, I noticed that it still returns generators. Any chance we can see a async-function spitting version on NPM some time?

**Comment by coderhaoxin** [comment]
`npm i koa-route@next`

**Comment by ronkorving** [comment]
Ah, would be nice if the readme could mention that like koa does. Thanks! :)
